pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '5.0.x'

- script: |
    dotnet build EntityFrameworkCore.DataEncryption.sln --configuration Release
  displayName: 'Build'

- script: |
    dotnet test EntityFrameworkCore.DataEncryption.sln --configuration Release
  displayName: 'Test'