pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '5.0.x'

# Build solution
- script: |
    dotnet build EntityFrameworkCore.DataEncryption.sln --configuration Release
  displayName: 'Build'

# Test solution
- script: |
    dotnet test EntityFrameworkCore.DataEncryption.sln --configuration Release /p:CollectCoverage=true /p:Exclude="[xunit*]*" /p:CoverletOutputFormat=opencover /p:CoverletOutput="../TestResults/TestResults.xml" /maxcpucount:1
  displayName: 'Test'

# Upload coverage
- script: |
    bash <(curl -s https://codecov.io/bash) -f ./test/TestResults/TestResults.xml
  displayName: 'Upload code coverage'

# Publish code coverage results as artifacts
- publish: $(System.DefaultWorkingDirectory)/test/TestResults
  artifact: CoverageResults
  displayName: 'Publish code coverage results'