language: csharp
mono: none
dotnet: 2.2.2
env:
- DOTNET_CLI_TELEMETRY_OPTOUT=1
- PROJECT_NAME="EntityFrameworkCore.Encryption"
matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
      name: Linux (Ubuntu Trusty)
    - os: osx
      name: Mac OS X
    - os: windows
      name: Windows

script:
  - dotnet restore
  - dotnet build ./src/$PROJECT_NAME/$PROJECT_NAME.csproj -c Release
  - dotnet test ./test/$PROJECT_NAME.Test/$PROJECT_NAME.Test.csproj -c Release