language: csharp
mono: none
dotnet: 3.1.403

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
    - PROJECT_NAME: "EntityFrameworkCore.DataEncryption"

jobs:
  include:
  - os: linux
    dist: xenial
    sudo: required
    name: ".NET Core 3 (Linux: Ubuntu Xenial)"
  - os: osx
    name: ".NET Core 3 (Mac: OS X)"
      
script:
  - dotnet build ./src/$PROJECT_NAME/$PROJECT_NAME.csproj -c Release -f netstandard2.1
  - dotnet test ./test/$PROJECT_NAME.Test/$PROJECT_NAME.Test.csproj -c Release -f netcoreapp3.0 /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[xunit*]*"

after_script:
  - bash <(curl -s https://codecov.io/bash) 