language: csharp
mono: none

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1

env:
  - PROJECT_NAME="EntityFrameworkCore.DataEncryption"

jobs:
  include:
  - os: linux
    dist: xenial
    sudo: required
    dotnet: 2.2.402
    env:
    - FRAMEWORK="netstandard2.0"
    - FRAMEWORK_TEST="netcoreapp2.2"
    name: ".NET Core 2 (Linux: Ubuntu Xenial)"
  - os: Linux
    dist: xenial
    sudo: required
    dotnet: 3.0.100
    env:
    - FRAMEWORK="netstandard2.1"
    - FRAMEWORK_TEST="netcoreapp3.0"
    name: ".NET Core 3 (Linux: Ubuntu Xenial)"
      

script:
  - dotnet restore
  - dotnet build ./src/$PROJECT_NAME/$PROJECT_NAME.csproj -c Release -f $FRAMEWORK
  - dotnet test ./test/$PROJECT_NAME.Test/$PROJECT_NAME.Test.csproj -c Release -f $FRAMEWORK_TEST /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[xunit*]*"

after_script:
  - bash <(curl -s https://codecov.io/bash) 