language: csharp
mono: none

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1

env:
  - PROJECT_NAME="EntityFrameworkCore.DataEncryption"

matrix:
  include:
    - os: linux
      sudo: required
      dist: xenial
      dotnet: 2.2
      name: .NET Core 2 : Linux (Ubuntu Xenial)
    - os: Linux
      sudo: required
      dist: xenial
      dotnet: 3.0.100
      name: .NET Core 3 : Linux (Ubuntu Xenial)
    - os: osx
      dotnet: 2.2
      name: .NET Core 2 : Mac OS X
    - os: osx
      dotnet: 3.0.100
      name: .NET Core 3 : Mac OS X

script:
  - dotnet restore
  - dotnet build ./src/$PROJECT_NAME/$PROJECT_NAME.csproj -c Release
  - dotnet test ./test/$PROJECT_NAME.Test/$PROJECT_NAME.Test.csproj -c Release /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[xunit*]*"

after_script:
  - bash <(curl -s https://codecov.io/bash) 