language: csharp
mono: none
dotnet: 2.2.105
env:
  global:
    - PROJECT_NAME="EntityFrameworkCore.Encryption"
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
  
matrix:
  include:
    - os: linux
      sudo: required
      dist: xenial
      name: Linux (Ubuntu Xenial)
    - os: osx
      name: Mac OS X

script:
  - dotnet restore
  - dotnet build ./src/$PROJECT_NAME/$PROJECT_NAME.csproj -c Release
  - dotnet test ./test/$PROJECT_NAME.Test/$PROJECT_NAME.Test.csproj -c Release